# Generated by Django 5.0.6 on 2024-07-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projectimage_is_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='is_logo',
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
    ]
